import type { SeriesSummary } from "./types";

// Sample data until Supabase is connected. Titles other than
// "Whispers In The Rain" are placeholders.
const days = (n: number) => new Date(Date.now() - n * 86400000).toISOString();

export const SAMPLE_SERIES: SeriesSummary[] = [
  {
    id: "1",
    slug: "whispers-in-the-rain",
    kind: "comic",
    title: "همسات في المطر",
    titleEn: "Whispers In The Rain",
    genre: "romance",
    publishDay: 4,
    coverUrl: null,
    tint: "#2B5CF6",
    creator: { id: "c1", name: "رنا قرني", verified: true },
    latestEpisode: { number: 12, publishedAt: days(2) },
    createdAt: days(90),
  },
  {
    id: "2",
    slug: "midan-al-saa",
    kind: "novel",
    title: "ميدان الساعة",
    titleEn: "Clock Square",
    genre: "mystery",
    publishDay: 6,
    coverUrl: null,
    tint: "#6B4DE6",
    creator: { id: "c2", name: "يوسف عادل", verified: true },
    latestEpisode: { number: 8, publishedAt: days(1) },
    createdAt: days(60),
  },
  {
    id: "3",
    slug: "genie-third-floor",
    kind: "comic",
    title: "جنّي الطابق الثالث",
    titleEn: "The Genie on the Third Floor",
    genre: "comedy",
    publishDay: 2,
    coverUrl: null,
    tint: "#FFB800",
    creator: { id: "c3", name: "سارة كمال", verified: false },
    latestEpisode: { number: 4, publishedAt: days(4) },
    createdAt: days(30),
  },
  {
    id: "4",
    slug: "sikkat-al-malh",
    kind: "novel",
    title: "سكة الملح",
    titleEn: "The Salt Road",
    genre: "historical",
    publishDay: 5,
    coverUrl: null,
    tint: "#FF7A59",
    creator: { id: "c4", name: "عمر حسن", verified: true },
    latestEpisode: { number: 21, publishedAt: days(1) },
    createdAt: days(200),
  },
  {
    id: "5",
    slug: "bint-al-nil",
    kind: "comic",
    title: "بنت النيل الأخير",
    titleEn: "The Last Daughter of the Nile",
    genre: "fantasy",
    publishDay: 0,
    coverUrl: null,
    tint: "#1E44C2",
    creator: { id: "c5", name: "نور محمود", verified: true },
    latestEpisode: { number: 3, publishedAt: days(6) },
    createdAt: days(20),
  },
  {
    id: "6",
    slug: "layl-al-madina",
    kind: "novel",
    title: "ليل المدينة",
    titleEn: "City Night",
    genre: "drama",
    publishDay: 3,
    coverUrl: null,
    tint: "#111111",
    creator: { id: "c6", name: "مريم الشريف", verified: false },
    latestEpisode: null,
    createdAt: days(3),
  },
];

/** Hand-ordered by the editor. */
export const SAMPLE_PICKS = ["1", "4", "2", "5"];
